# Generated by Django 3.0.2 on 2020-01-20 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200119_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sign_in_status',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='sign in status'),
        ),
    ]
