# Generated by Django 3.0.2 on 2020-01-25 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200125_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Client'),
        ),
        migrations.AlterField(
            model_name='user',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Location'),
        ),
        migrations.DeleteModel(
            name='Workplace',
        ),
    ]
