# Generated by Django 3.0.2 on 2020-01-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200125_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channel_name',
            field=models.TextField(blank=True, null=True, verbose_name='channel name'),
        ),
    ]
