# Generated by Django 3.0.2 on 2020-01-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_channel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='channel_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='channel name'),
        ),
    ]
