# Generated by Django 3.0.2 on 2020-01-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200125_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='busy',
        ),
    ]
