# Generated by Django 3.0.2 on 2020-01-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_user_busy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='busy',
            field=models.BooleanField(default=False),
        ),
    ]
